Update deployment.yml

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -67,6 +67,25 @@ jobs:
           S3_ACCESS_KEY: ${{ secrets.IAM_ACCESS_KEY_ID }} 
           S3_SECRET_KEY: ${{ secrets.IAM_SECRET_ACCESS_KEY }}
         run: |
+            # Path to your private key in the repo
+            KEY_PATH="pem/my-terraform-key.pem"
+            
+            # Ensure SSH key exists
+            if [[ ! -f "$KEY_PATH" ]]; then
+              echo "Error: SSH key not found at $KEY_PATH"
+              exit 1
+            fi
+            
+            # --- SSH Key Setup ---
+            echo "Setting up SSH key..."
+            mkdir -p ~/.ssh
+            cp "$KEY_PATH" ~/.ssh/id_rsa
+            chmod 400 ~/.ssh/id_rsa
+            
+            # Disable strict host key checking (avoid CI host verification failure)
+            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
+            ## Copy files
+            scp -i ~/.ssh/id_rsa yml/*.yml ubuntu@$EC2_IP:/home/ubuntu/deployments/
             ssh -i ~/.ssh/id_rsa ubuntu@$EC2_IP "EC2_IP='${EC2_IP}' bash -s" << 'EOF'
             env | grep EC2
             EOF
