Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -57,15 +57,90 @@ jobs:
           IMAGE=ghcr.io/${{ github.repository }}:v1
           docker build -t $IMAGE .
           docker push $IMAGE
+      - name: Setup SSH key
+        run: | 
+          mkdir -p ~/.ssh
+          cp pem/my-terraform-key.pem ~/.ssh/id_rsa
+          chmod 400 ~/.ssh/id_rsa
+          # Disable strict host key checking to avoid host verification failure in CI
+          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
+      - name: Login to EC2
+        run: |
+            ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+              if ! sudo docker version &> /dev/null
+              then
+                  echo "Docker not found. Installing..."
+                  # Update apt and install prerequisite packages
+                  sudo apt-get update -y
+                  sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
           
-      - name: Print EC2 Public IP
-        run: echo "${{ secrets.EC2_PUBLIC_IP }}"
+                  
+          
+                  # Add Docker's official GPG key
+                  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
+    
+                  # Add Docker apt repository
+                  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
+          
+                  
+          
+                  # Update apt again to include Docker repo packages
+          
+                  sudo apt-get update -y
+          
+                  
+          
+                  # Install Docker Engine, CLI, containerd, and Docker Compose plugin
+          
+                  sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
+          
+            
+          
+              else
+          
+                  echo "Docker is already installed."
+          
+              fi   
+          
+              # Check Docker Compose 
+          
+              if ! sudo docker compose version &> /dev/null
+          
+              then
+          
+                  echo "Docker Compose not found. Installing..."
+          
+                  sudo apt-get install docker-compose-plugin -y
+          
+              else
+          
+                  echo "Docker Compose is already installed."
+          
+              fi
+          
+              
+          
+              # Start and enable Docker
+          
+              
+          
+              echo "Starting Docker..."
+          
+              sudo systemctl enable docker
+          
+              sudo systemctl start docker
+          
+              sudo systemctl status docker --no-pager
+          
+              echo *** | sudo docker login ghcr.io -u sanjay812 --password-stdin
+          
+              cd /home/ubuntu/deployments
+          
+              sudo mkdir -p ./loki-data
+          
+              sudo chown -R 10001:10001 ./loki-data
+        
+            EOF
 
       - name: Print S3 Bucket Name
         run: echo "S3 Bucket:${{ secrets.S3_BUCKET_NAME }}"
-
-      - name: Print IAM Access Key
-        run: echo "IAM Access Key:${{ secrets.ACCESS_KEY }}"
-
-      - name: Print IAM Secret Key
-        run: echo "IAM Secret:${{ secrets.SECRET_KEY }}"
