Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -44,29 +44,30 @@ jobs:
 
    ##EC2
     - name: ec2 connect
-      chmod 400 pem/key-rsa.pem
-      scp -i pem/key-rsa.pem yml/*.yml ubuntu@3.108.64.74:/home/ubuntu/deployments/
-      ssh -i pem/key-rsa.pem ubuntu@3.108.64.74
-      # Check Docker
-      if ! sudo docker version &> /dev/null
-      then
-          echo "Docker not found. Installing..."
-          sudo apt-get install docker.io     
-      else
-          echo "Docker is already installed."
-      fi   
-      # Check Docker Compose 
-      if ! sudo docker compose version &> /dev/null
-      then
-          echo "Docker Compose not found. Installing..."
-          sudo apt-get install docker-compose-plugin -y
-      else
-          echo "Docker Compose is already installed."
-      fi
-      
-      # Start and enable Docker
-      
-      echo "Starting Docker..."
-      sudo systemctl enable docker
-      sudo systemctl start docker
-      sudo systemctl status docker --no-pager
+      run: |
+        chmod 400 pem/key-rsa.pem
+        scp -i pem/key-rsa.pem yml/*.yml ubuntu@3.108.64.74:/home/ubuntu/deployments/
+        ssh -i pem/key-rsa.pem ubuntu@3.108.64.74
+        # Check Docker
+        if ! sudo docker version &> /dev/null
+        then
+            echo "Docker not found. Installing..."
+            sudo apt-get install docker.io     
+        else
+            echo "Docker is already installed."
+        fi   
+        # Check Docker Compose 
+        if ! sudo docker compose version &> /dev/null
+        then
+            echo "Docker Compose not found. Installing..."
+            sudo apt-get install docker-compose-plugin -y
+        else
+            echo "Docker Compose is already installed."
+        fi
+        
+        # Start and enable Docker
+        
+        echo "Starting Docker..."
+        sudo systemctl enable docker
+        sudo systemctl start docker
+        sudo systemctl status docker --no-pager
